name: example
description: Exmaple of cached_video_preview flutter package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_video_preview:
    path: ../
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/video.mp4
